/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 scene.gltf --transform --t 
Files: scene.gltf [19.34KB] > /Users/crow/Desktop/crow/crow-test/toss-cat-practice/public/cat_with_a_gun/scene-transformed.glb [46.64KB] (-141%)
Author: Bluenoseddonkey (https://sketchfab.com/Bluenoseddonkey)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cat-with-a-gun-70df1c27fc424871b8fce0925e1d4429
Title: Cat with a gun
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'Take 001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_7: THREE.SkinnedMesh
    Object_9: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    base: THREE.MeshStandardMaterial
    GunBase: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { scene } = useGLTF('/scene-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials, animations } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.base} skeleton={nodes.Object_7.skeleton} scale={0.01} />
        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.GunBase} skeleton={nodes.Object_9.skeleton} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
