/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 scene.gltf --transform --t 
Files: scene.gltf [84.96KB] > /Users/crow/Desktop/crow/crow-test/toss-cat-practice/public/trumph/scene-transformed.glb [74.36KB] (12%)
Author: Denys Almaral (https://sketchfab.com/denysalmaral)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/lowpoly-trump-free-character-ba7b382c918b40e6b07011da4ff3ebc0
Title: LowPoly Trump Free Character
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'Take 001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_34: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    TrumpLPmat: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { scene } = useGLTF('trumph/scene-transformed-v1.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials, animations } = useGraph(clone) as GLTFResult
  // const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null} position={[0,0,0]}>
      <group name="Sketchfab_Scene">
        <group name="RootNode">
          <group name="trump_rigCharRoot">
            <group name="Object_5">
              <primitive object={nodes._rootJoint} scale={5} />
              <skinnedMesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.TrumpLPmat} skeleton={nodes.Object_34.skeleton} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('trumph/scene-transformed-v1.glb')

/**
 * glb 파일
 * unknown extension "khr_materials_pbrspecularglossiness" 에러나는 경우
 * https://gltf.report/ 를 변환해줌
 */

